# Generated by Django 3.0.7 on 2020-08-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=250)),
                ('celular', models.CharField(default='999999999', max_length=15)),
                ('direccion', models.TextField(default='Direccion', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('mascota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('raza', models.CharField(default='', max_length=70)),
                ('altura', models.CharField(default='', max_length=70)),
                ('tipo', models.CharField(default='', max_length=70)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('turno_id', models.AutoField(primary_key=True, serialize=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Mascota')),
            ],
        ),
    ]
