# Generated by Django 3.0.7 on 2020-08-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20200815_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
    ]
