# Generated by Django 3.0.7 on 2020-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20200815_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='En Espera', max_length=70),
        ),
    ]
